---
title: "Capstone - Final Project"
author: "Daniel Cevallos"
date: "2023-07-14"
output: ioslides_presentation
---

## Introduction

The goal of this exercise is to create a product to highlight the prediction algorithm that you have built and to provide an interface that can be accessed by others. For this project you must submit:

1. A Shiny app that takes as input a phrase (multiple words) in a text box input and outputs a prediction of the next word.

2. A slide deck consisting of no more than 5 slides created with R Studio Presenter (https://support.rstudio.com/hc/en-us/articles/200486468-Authoring-R-Presentations) pitching your algorithm and app as if you were presenting to your boss or an investor.

## Data Analysis

The library [Quandeta](https://tutorials.quanteda.io/) was employed to perform the text analysis:

- Construct a tokens object
- Keyword-in-contexts
- Select tokens
- Compound tokens
- Look up dictionary
- Genarate n-grams

15% of the **en_US.news.txt** was considered due to computational performance. 

## Shiny Text Predictor application

The application developed can predict the next possible words for the inserted sentence.

It is based on the simplicity of adding the desired sentence in the blank box and press submit. In a few seconds the application shows the possible predicted words for your sentence.

The algorithm works with n-grams files in which are divided into 2, 3 and 4 grams sequences. The input is compared with the tokenized frequency of the n-grams files.

## Github and Shiny app Text Predictor website:

[Github codes' repository ](https://github.com/danny2983/finalSubmitSwift)

[The Shiny App - Text Predictor](https://danny2983.shinyapps.io/finalSubmitSwift/)